title = "MontyCraig Secret Scanning Rules"

[extend]
useDefault = true

[allowlist]
description = "MontyCraig Allowlist"
paths = [
    '''^\.secrets\.baseline$''',
    '''^\.env\.example$''',
    '''^node_modules/.*$''',
    '''^__pycache__/.*$''',
]
